import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <br />
        <div className="h-5" />
        <div className="px-10 py-5 min-h-[calc(110vh-160px)] bg-white">
          {" "}
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
